var express = require('express')
var router = express.Router()
var users=require("../controllers/users.controller")
router.route("/isLogin")
  .get(users.isLogin)
router.route("/register")
  .post(users.register)
router.route("/login")
  .post(users.login)
router.route("/logout")
  .get(users.logout)
router.route("/validateName")
  .post(users.validateName)
router.route('/addToCart')
	.post(users.addToCart)
router.route('/getCart')
	.get(users.getCart)
router.route('/deleteOneItem')
	.get(users.deleteOneItem)
router.route('/deleteSome')
	.get(users.deleteSome)
router.route('/deleteAll')
	.get(users.deleteAll)
router.route('/selectAll')
	.post(users.selectAll)
router.route('/search')
	.get(users.search)
module.exports = router
